### ISSUE TITLE
unused argument (nThread = if (n_threads == "max") {

### ISSUE THREAD

**Issue by jielab** [kenhanscombe/ukbtools#11]
Hi, I used the following code to install the latest development version: devtools::install_github("kenhanscombe/ukbtools", build_vignettes = TRUE, dependencies = TRUE) 

and then run the following two lines:
> library(ukbtools)
> my_ukb_data <– ukb_df("ukb9820", path="/restricted/projectnb/ukbiobank/jiehuang/data/ukb/pheno/raw")

Bub I still got the following error:
Error in data.table::fread(input = tab_location, sep = "\t", header = TRUE,  :
  unused argument (nThread = if (n_threads == "max") {
    parallel::detectCores()
} else if (n_threads == "dt") {
    data.table::getDTthreads()
} else if (is.numeric(n_threads)) {
    min(n_threads, parallel::detectCores())
})

**Comment by kenhanscombe** [comment]
Hi,

See closed issue #10 . You need to update `data.table`.

Let me know if this resolves you read problem.

All the best,

Ken
