### ISSUE TITLE
Error with ukb_df in latest version

### ISSUE THREAD

**Issue by hilge** [kenhanscombe/ukbtools#12]
Hi Ken,

After installing your latest version (either the development or the CRAN one) i get the following error when running ukb_df.

>   my_ukb <- ukb_df(paste0(datasetname,".sub"))
Error in mutate_impl(.data, dots) :
  Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.
Please use `as_data_pronoun()` instead.

**Comment by kenhanscombe** [comment]
Hi Johan,

Sorry for the delay.

It's a dplyr issue (https://community.rstudio.com/t/trouble-using-mutate-and-other-functions-after-update/17066/7). Try the fix they suggest:

```update.packages(ask = FALSE, checkBuilt = TRUE)```

Let me know how it goes.

Ken

**Comment by hilge** [comment]
Great thanks, for that, I am away but will try this out in the weekend or beginning next week. Will let you know how it goes.

Best, J

**Comment by hilge** [comment]
Hi Ken that did solve the first problem thank. But I get a second warning now which I dont really know how to handle. 

>  my_ukb <- ukb_df(paste0(datasetname,".sub"))
|--------------------------------------------------|
|==================================================|
Error in `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  :
  factor level [4] is duplicated

Have you come across this before, happy to open this as a new issue (since its proberbly unrelated) if you think thats usefull.

Best,
J

**Comment by supermaheroo** [comment]
Hi Ken. I am having the same issue as Hilge was having. I updated the packages yesterday using `update.packages(ask = FALSE, checkBuilt = TRUE)` and didn't help. Will try from alternative computer.

**Comment by supermaheroo** [comment]
Hi. Have tried different computer and that's what I got. 

|--------------------------------------------------|
|==================================================|
Error in `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  : 
  factor level [4] is duplicated
In addition: Warning messages:
1: package ‘bindrcpp’ was built under R version 3.4.4 
2: In data.table::fread(input = tab_location, sep = "\t", header = TRUE,  :
  Discarded single-line footer: <<1300032	1	1	NA	NA	0	NA	NA	0	1949	1	NA	NA	"002817"	NA	NA	""	NA	NA	"000196"	NA	NA	"002894"	NA	NA	"001201"	NA	NA	"001161"	NA	NA	"03080"	NA	NA	"002452"	NA	NA	16	NA	NA	19	NA	NA	79	NA	NA	99	NA	NA	164	NA	NA	139	NA	NA	5	2008-03-05	NA	NA	11006	NA	NA	6	NA	NA	3	NA	NA	NA	-0.118	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA>>

**Comment by hilge** [comment]
I belive this has to do with coding in speicif variables, as its only an issue that arises from a subset of our variables. That is the ukb_df commands runs fine on most of the variables. If helpfull I can try and identify which specific variables it is that makes the function fall over.

**Comment by kenhanscombe** [comment]
Thanks Johan.

Sorry for the delay in replying. As you say, it looks like the problem arises where particular factors have duplicated levels, in the UKB supplied levels in the html file. I've pasted below a conversation I've been having with another user over email (my response at top).

I'll have a look to see if there is something I can do to resolve these duplicates in some generic way when reading in the data – perhaps with a warning instead.

(Still worth checking with UKB what the levels should be for problem variables in your particular study)

> Re. the factor, yes, it looks like 'Cancer information source (Encoding ID 262)' has duplicated levels in the UKB showcase. Best to ask UKB if this is intentional before changing anything.
> 
> Re. the read error, I think this is to do with mismatching quotes in the tab file. It is a data error, but different versions of data.table::fread seem to handle it differently. Try updating to the latest data.table, 1.11.8, and let me know if this makes any difference. It is only a warning, so does the read still work?  (I guess you might have to change one of the levels in the .r file for the problematic categorical variable and make a note of it, so that you can see if the read works ok)
> 
> 
> All the best,
> 
> Ken
> 
> 
> (...) wrote:
> 
> Dear Ken,
> I used before ukbtools successfully. But now, it doesn’t. I think it stop working after installing latest version (0.11.0), but I’m not sure this is the cause.
> I’m loading using next command:
> my_ukb_data <- ukb_df(FNAME, path=PATH)
> 
> But then I get the next error and warning:
> 
> Error in `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  :
> factor level [4] is duplicated
> In addition: Warning message:
> In data.table::fread(input = tab_location, sep = "\t", header = TRUE,  :
> Found and resolved improper quoting out-of-sample. First healed line 30009: <<1300080	354	NA	NA	797	NA	NA	491	NA	NA	126	NA	NA	1NA	NA	0	NA	NA	0	1943	20	NA	NA	24	NA	NA	70	NA	NA	94	NA	NA	171	NA	NA	5	2008-09-04	NA	NA	11012	NA	NA	1	NA	NA	NA	-0.348	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	105	286	NA	NA	NA	NA	59	61	NA	NA	NA	NA	0	NA	9	NA	NA	130500	NA	NA	414500	NA	NA	NA	NA	NA	0	NA	NA	0	NA	NA	1	NA	NA	0	NA	NA	6.89374	3	4	NA	NA	NA	NA	NA	NA	NA	2	3	NA	NA	NA	NA	3	6	NA	NA	NA	NA	NA	NA	NA	0	5	NA	NA	NA	NA	NA	NA	NA	82	584	NA	NA	NA	NA	NA	NA	NA	7	7	5	87	0	1	3	6	7	2	5	NA	NA	NA	NA>>. If the fields are not quoted (e.g. field separator does not appear within any field), try quote="" to avoid this warning.
> 
> Can you please help me with that?
> I’m not sure if it’s a bug in the package, or a problem with the data I download. But as I mentioned, it worked previously.
> 
> I now found that in the ukbxxx.r file there are two factor identical levels for field 40019 labeled "Scottish Cancer Registry (fixed width format) 2012 onwards”. 
> 
> I wrote UKBB support asking about that.
> 
> But how about the "improper quoting”, have you seen this warning before?

**Comment by nadavrap** [comment]
I also have this issue. I found that in the ukbxxx.r file there are two identical factor levels for field 40019 labeled "Scottish Cancer Registry (fixed width format) 2012 onwards”. 
This is related to Data-Coding 262 (See [here](http://biobank.ctsu.ox.ac.uk/crystal/coding.cgi?id=262).
A workaround would be to change the ukbxxx.r file for the second level to be some unique value.
I wrote UKBB support about that, but I haven't heard back from them.

**Comment by kenhanscombe** [comment]
Given these are typos in UKB data, it's probably best to resolve them like this, making a decision what to change the level to and recording what you've changed. You can identify categorical variables with duplicated levels with a regex search on either in the .html file or the .r file Possibly easier on the .r file because all variables will recoded with 3 lines of code (level assignment, label assignment, then conversion to factor):

```
lvl.100688 <- c(-7,-3,-1,1,2,3,4,5)
lbl.100688 <- c("None of the above","Prefer not to answer","Do not know","Aspirin","Ibuprofen (e.g. Nurofen)","Paracetamol","Codeine","Ranitidine (e.g. Zantac)")
bd$f.10004.0.0 <- ordered(bd$f.10004.0.0, levels=lvl.100688, labels=lbl.100688)
```

**NB.** Remember: the UKB-generated **.r file converts all categorical variables to ordered factors**. In most cases, you definitely **do not** want an ordered factor, e.g., the variable shown above. This is not a good default conversion. You should convert to unordered factors, variables that have no meaningful order.

**Comment by hilge** [comment]
Thanks for this Ken, very useful.

**Comment by nadavrap** [comment]
I recently received an official reply to my question from UKBB support:

> ...regarding data coding 262 … This is a duplication caused by the way the data was originally entered into the system. Codes 4 and 22 should simply both be treated as coming from the Scottish 
> Cancer Registry (neither is in fact limited to 2012 onwards). There is a plan to re-code 
> these fields, combining 4 and 22 together (and 3 and 23 together as well), but this is 
> not likely to be a high priority in the immediate future.

I hope it helps.
