### ISSUE TITLE
importing the data partially after ukb_df function 

### ISSUE THREAD

**Issue by supermaheroo** [kenhanscombe/ukbtools#13]
Thanks Ken for creating this package. I tried to import my data using Ukb_df function, but the data base produced is only 16089 observations and my data set is about 500,000. Do you know what could be the reason for this discrepancy? 

Maher,

**Comment by kenhanscombe** [comment]
Hi Maher,

Sorry for the delay. Were you able to resolve the issue?

Ken

**Comment by FeFortti** [comment]
Hello! I have the same error. I have about 500,000 observations (eid), but "my_ukb_data" only contain 12152 observations.

Besides that, I get the warning: 

my_ukb_data <- ukb_df("ukbxxxxx")
Warning: `data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.
Warning in data.table::fread(input = tab_location, sep = "\t", header = TRUE,  :
  Discarded single-line footer: <<4356529	1	NA	NA	NA	0	1941	1	NA	NA	NA	22	NA	NA	NA	24	NA	NA	NA	79	NA	NA	NA	96	NA	NA	NA	164	NA	NA	NA	135	NA	NA	NA	7	2009-06-03	NA	NA	NA	11010	NA	NA	NA	6	NA	NA	NA	4	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	>>
