### ISSUE TITLE
Error in html_table_nodes[[data.pos]] : subscript out of bounds

### ISSUE THREAD

**Issue by kenhanscombe** [kenhanscombe/ukbtools#14]
Hello, Thank you for creating the ukbtools package. 
The current issue I am facing is 
Error in html_table_nodes[[data.pos]] : subscript out of bounds
In addition: Warning message:
XML content does not seem to be XML: './ukb26###.html'
I have moved all the files to the same drive, and re-converted the files using conv. 
Any ideas what may be causing this?
Thanks heaps, Mahima

_Originally posted by @mkapoor123 in https://github.com/kenhanscombe/ukbtools/issues/1#issuecomment-461099610_

**Comment by kenhanscombe** [comment]
Hi Mahima,

It's probably a typo.

XML is saying the file specified is not XML format – translation: there is no file where you are pointing. I'd need to see the command you typed. Did you specify the full path to the directory containing the  r, tab, html files? See the example **Making a dataset** in the vignette https://kenhanscombe.github.io/ukbtools/articles/explore-ukb-data.html

If you download the development version
```
devtools::install_github("kenhanscombe/ukbtools", build_vignettes = TRUE, dependencies = TRUE)
```
you can try loading the included example fileset (described under **An example fileset** in the vignette)

Let me know how you get on.

All the best,

Ken

**Comment by mkapoor123** [comment]
Hi, 
These are the ways I have tried to use it..
> library(ukbtools)
> my_ukb_data <- ukb_df("ukb26439", path = "Users/mahimakapoor/Mahima's Documents/Biobank UK")
Error in html_table_nodes[[data.pos]] : subscript out of bounds
In addition: Warning message:
XML content does not seem to be XML: 'Users/mahimakapoor/Mahima's Documents/Biobank UK/ukb26439.html' 
> my_ukb_data <- ukb_df("ukb26439", path = "Macintosh HD/Users/mahimakapoor/Mahima's Documents/Biobank UK")
Error in html_table_nodes[[data.pos]] : subscript out of bounds
In addition: Warning message:
XML content does not seem to be XML: 'Macintosh HD/Users/mahimakapoor/Mahima's Documents/Biobank UK/ukb26439.html' 
> my_ukb_data = ukb_df("ukb26439", path = "Macintosh HD/Users/mahimakapoor/Mahima's Documents/Biobank UK")
Error in html_table_nodes[[data.pos]] : subscript out of bounds
In addition: Warning message:
XML content does not seem to be XML: 'Macintosh HD/Users/mahimakapoor/Mahima's Documents/Biobank UK/ukb26439.html' 
>

Thanks for your help!
Mahima

**Comment by kenhanscombe** [comment]
Hi Mahima,

Those paths look incorrect.

You have a missing root (`/` at the front of the path), you've not escaped the spaces (e.g. `Biobank\\ UK`, I think it's a double backslash to escape), and there are probably no apostrophes in you directory tree. (Avoid spaces in your directory names)

**Note**: If you type `list.files("path/to/files")` with the string you've used for the `path` argument, you should see your UKB fileset. If not, you have not specified the path correctly.

It looks like you're using a Mac. Open a Terminal window, and in Finder, open the folder containing your files. Drag the folder icon to the Terminal and you should see the path. Copy and paste that into the R function `list.files`.

Alternatively, to build the right path step-by-step, use R `list.files` and TAB autocompletion. In R, type `list.files("/Us` press TAB, which should show you a list of files and directories to select. Press TAB again if you don't see a list (if nothing appears you have a typo, go back a step). Continue in this way till you reach your UKB fileset enclosing folder. Type `")` to close `list.files` and press Enter.

All the best,

Ken

**Comment by mkapoor123** [comment]
Thanks for the help about the path, that worked perfectly. Mahima

**Comment by mkapoor123** [comment]
Sorry to ask another question, I wonder if you might have some further advice. I am having trouble creating a subset for column 992 (operation codes) who have had a certain procedure, the code of which is X302. Cheers
