### ISSUE TITLE
Use vroom instead of data.table::fread for faster loading?

### ISSUE THREAD

**Issue by lwjohnst86** [kenhanscombe/ukbtools#19]
New package [vroom](https://github.com/r-lib/vroom) out that is much faster than fread at mixed data (aka, not only numerical) and that also supports the wonderful features found in readr. Maybe switch over to vroom instead?

**Comment by lwjohnst86** [comment]
And also, thanks for the package :wink:

**Comment by kenhanscombe** [comment]
Thanks for the suggestion. I'll have a look at switching to vroom.
