### ISSUE TITLE
ukbtools

### ISSUE THREAD

**Issue by KelvinAA** [kenhanscombe/ukbtools#22]
Hello there,

I have read the other post about error in using the ukb_df command but have tried specifying the path to the file without success.

I have done 

> devtools::install_github("kenhanscombe/ukbtools", build_vignettes = TRUE, dependencies = TRUE)
>library(ukbtools)
>ukb_dataset <- ukb_df("ukb29xxx-4", path = "/Users/workspace/monday/DH")

But keep getting the following and no matter how i've tweaked it it just doesn't work.
Error in html_table_nodes[[data.pos]] : subscript out of bounds
In addition: Warning message:
XML content does not seem to be XML: './ukb29xxx-4.tab.html' 

I have also  used
> path_to_example_data <- system.file("extdata", package = "ukbtools")
> df <- ukb_df("ukbxxxx", path = path_to_example_data)
> df_field <- ukb_df_field("ukbxxxx", path = path_to_example_data)

and it does work with the example (just not the actual data)

Please do you have any advice?

Thanks a lot,
K

**Comment by kenhanscombe** [comment]
Sorry for the delay. Did you manage to resolve this. It looks like a path/ file issue. Let me know if I can help.
