### ISSUE TITLE
problem with ukb_context

### ISSUE THREAD

**Issue by alrodrig11** [kenhanscombe/ukbtools#24]
Hello,
I'm currently using the ukb_context function and I keep getting the following error:

```
Error: No expression to parse
Call `rlang::last_error()` to see a backtrace. 
```

I've tried to using dplyr::select and it appears to be grabbing all the correct columns for the demographics data and the nomiss.var is definitely in the referenced dataset. I even tried
setting all the demographic columns manually, but still no luck. Here is the code I ran. Any insight would be appreciated:

```
ukbxxxx_data <- ukb_df("ukbxxxx_symp", path = "/Users/amandarodrigue/Dropbox/Biobank_symp/Psychotic_experiences/")
ukbyyyy_data <-ukb_df("ukbyyyy_symp", path = "/Users/amandarodrigue/Dropbox/Biobank_symp/Psychotic_experiences/")

full_data<-ukb_df_full_join(ukbxxxx_data, ukbyyyy_data)

ukb_context(full_data, nonmiss.var = "volume_of_brainseg_whole_brain_f26514_2_0",
            bar.position = "fill", sex.var = "sex_f31_0_0",
            age.var = "age_when_attended_assessment_centre_f21003_0_0",
            socioeconomic.var = "townsend_deprivation_index_at_recruitment_f189_0_0",
            ethnicity.var = "ethnic_background_f21000_0_0",
            employment.var = "current_employment_status_corrected_f20119_0_0",
            centre.var = "uk_biobank_assessment_centre_f54_0_0")
```
I've also tried the ukb_context with a subset of data and get the same error.

**Comment by kenhanscombe** [comment]
Apologies. I was not able to reproduce the error. If you'd still like to use this function please try intall the development version of the package. (I'm now updating/refactoring all the ukbtools code.)

```
devtools::install_github("kenhanscombe/ukbtools", dependencies = TRUE, force = TRUE)
```
