### ISSUE TITLE
ukb_centre

### ISSUE THREAD

**Issue by tra6sdc** [kenhanscombe/ukbtools#25]
Hello, I used `ukb_centre` to add the assessment centre as a text string. Looking at the frequencies this doesn't look right. 
````
> table(my_ukb_data$ukb_centre)

            Barts        Birmingham           Bristol              Bury           Cardiff 
             3797             13939             14058             17878             18647 
Cheadle (revisit)           Croydon         Edinburgh           Glasgow          Hounslow 
            17198             19433             29411             28321             37002 
            Leeds         Liverpool        Manchester    Middlesborough         Newcastle 
            44198             43012             12582             33876             30396 
       Nottingham            Oxford           Reading         Sheffield Stockport (pilot) 
            32816             21286             28875             27380             25501 
            Stoke           Swansea 
             2281               649 
````
For example, comparing with the showcase count https://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=54, Birmingham has 25,501 participants, the count for Stockport (pilot) here.

**Comment by kenhanscombe** [comment]
Sorry for the delay.

I have no idea why this happened. New centres have been added, but if anything I would have expected `NA` for unknown centres. I've now updated the centre information to include the current list of 27 centres, included in the package dataset `ukbcentre`.

Please install the dev version

```
devtools::install_github("kenhanscombe/ukbtools", dependencies = TRUE, force = TRUE)
```

 and test the centre count again.
