### ISSUE TITLE
Inconsistent prevalence results

### ISSUE THREAD

**Issue by dspagnolo09** [kenhanscombe/ukbtools#27]
I was trying my hand at using the ukb_icd_prevalence function with a regular expression and I got some inconsistent results when checking it exhaustively against all the codes I was interested in. 

Code below:
`x <- ukb_icd_prevalence(my_ukb_data, icd.code = "K85.*",  icd.version = 10)`

`y <- (ukb_icd_prevalence(my_ukb_data, icd.code = "K85",  icd.version = 10) +
        ukb_icd_prevalence(my_ukb_data, icd.code = "K850", icd.version = 10) +
        ukb_icd_prevalence(my_ukb_data, icd.code = "K851", icd.version = 10) +
        ukb_icd_prevalence(my_ukb_data, icd.code = "K852", icd.version = 10) +
        ukb_icd_prevalence(my_ukb_data, icd.code = "K853", icd.version = 10) +
        ukb_icd_prevalence(my_ukb_data, icd.code = "K854", icd.version = 10) +
        ukb_icd_prevalence(my_ukb_data, icd.code = "K855", icd.version = 10) +
        ukb_icd_prevalence(my_ukb_data, icd.code = "K856", icd.version = 10) +
        ukb_icd_prevalence(my_ukb_data, icd.code = "K857", icd.version = 10) +
        ukb_icd_prevalence(my_ukb_data, icd.code = "K858", icd.version = 10) +
        ukb_icd_prevalence(my_ukb_data, icd.code = "K859", icd.version = 10))`

I found the prevalence of **x** to be smaller in my dataset than the prevalence of **y**. This is confusing to me as K85.* should cover all the codes I was looking up in **y**. If anything I expected **y** to maybe be smaller than **x**, to account for K85.00, K85.01 etc. and other sub-codes I may have not included (but did not see in the dataset from a cursory overview). 

I am not sure which result to trust. **x** is 0.0045 and **y** is 0.0066. Thoughts?

**Comment by kenhanscombe** [comment]
Hi,

Sorry for the delay. In your second calculation of the prevalence, you are counting some codes more than once.

The value you give to `icd.code` is a regex. One way to sense check the regular expression you provide is to check it against the icd datasets included in the package, e.g.,

```
icd10codes %>% filter(str_detect(code, "K85.*"))

  code                                  meaning
1  K85                   K85 Acute pancreatitis
2 K850      K85.0 Idiopathic acute pancreatitis
3 K851         K85.1 Biliary acute pancreatitis
4 K852 K85.2 Alcohol-induced acute pancreatitis
5 K853    K85.3 Drug-induced acute pancreatitis
6 K858           K85.8 Other acute pancreatitis
7 K859    K85.9 Acute pancreatitis, unspecified
```

`icd.code = "K85"` returns the same  as `icd.code = "K85.*"`

```
icd10codes %>% filter(str_detect(code, "K85"))

  code                                  meaning
1  K85                   K85 Acute pancreatitis
2 K850      K85.0 Idiopathic acute pancreatitis
3 K851         K85.1 Biliary acute pancreatitis
4 K852 K85.2 Alcohol-induced acute pancreatitis
5 K853    K85.3 Drug-induced acute pancreatitis
6 K858           K85.8 Other acute pancreatitis
7 K859    K85.9 Acute pancreatitis, unspecified
```

To retrieve the prevalence for just "K85" in the second  calculation

```
icd10codes %>% filter(str_detect(code, "K85$"))

  code                meaning
1  K85 K85 Acute pancreatitis
```

Your first calculation is "correct", but I would definitely recommend checking the icd dataset to make sure you're picking up the diagnoses you think you're picking up.

Hope that helps
