### ISSUE TITLE
Fewer observations than expected

### ISSUE THREAD

**Issue by FeFortti** [kenhanscombe/ukbtools#28]
Hello! I have the same error. I have about 500,000 observations (eid), but "my_ukb_data" only contain 12152 observations.

Besides that, I get the warning: 

my_ukb_data <- ukb_df("ukbxxxxx")
Warning: `data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.
Warning in data.table::fread(input = tab_location, sep = "\t", header = TRUE,  :
  Discarded single-line footer: <<4356529	1	NA	NA	NA	0	1941	1	NA	NA	NA	22	NA	NA	NA	24	NA	NA	NA	79	NA	NA	NA	96	NA	NA	NA	164	NA	NA	NA	135	NA	NA	NA	7	2009-06-03	NA	NA	NA	11010	NA	NA	NA	6	NA	NA	NA	4	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	>>

_Originally posted by @FeFortti in https://github.com/kenhanscombe/ukbtools/issues/13#issuecomment-647046788_

**Comment by kenhanscombe** [comment]
Hello, sorry for the delay.

If you've not resolved the issue, please try install the development version. (I have a few more things I'd like to add before I release as the next CRAN update.)

`devtools::install_github("kenhanscombe/ukbtools", dependencies = TRUE)`

Please let me know what you get with the dev version.
