### ISSUE TITLE
ukb_gen_write_bgenie  -  Error in UseMethod("left_join") 

### ISSUE THREAD

**Issue by curranth** [kenhanscombe/ukbtools#3]
Hi, I have been trying to use your package to write a covariates table for use with BGENIE. Whilst doing so I encountered the following problem:

I loaded my data in using:
 biobank_data <- ukb_df("ukb_key")
bgenie_covars <- ukb_gen_write_bgenie(biobank_data, "path_to_sample_file", "path_to_output_file", list_of_biobank_variables)

And received the error message:

Error in UseMethod("left_join") : 
  no applicable method for 'left_join' applied to an object of class "character"

Any help would be greatly appreciated!

**Comment by kenhanscombe** [comment]
Hi,

You need to supply `ukb_gen_write_bgenie` the sample file as a dataframe. You will also need to explicitly select the columns you would like written to the BGENIE file.

```{r}
my_ukb_sample <- ukb_gen_read_sample("path_to_sample_file")

ukb_gen_write_bgenie(
   my_ukb_data,
   ukb.sample = my_ukb_sample,
   ukb.variables = c("height", "weight", "iq")
   path = "my_ukb_bgenie.pheno",
)
```

Sorry, I made a typo in the documentation. It should have been: `ukb.sample` A sample file. (*Not: Path to ...*). If you look at the examples you can see that I first read the sample file in. Your sample file is a rectangular file with two header lines. Using `ukb_gen_read_sample` will read it in correctly and label the columns.

Let me know if this fixes your problem.

All the best,

Ken

**Comment by kenhanscombe** [comment]
Hi,

I've updated the documentation in the development version v0.10.1.9000. To install the development version

```
devtools::install_github("kenhanscombe/ukbtools", build_vignettes = TRUE, dependencies = TRUE)`)
```

 The functionality remains exactly the same as the CRAN version, v0.10.1

Let me know if there is any other functionality you would find useful.

All the best,

Ken

**Comment by curranth** [comment]
Hi Ken, 

Thanks for all your help so far. 

Unfortunately, upon downloading the latest version, I am no longer able to load the dataset and am receiving errors when using ukb_df. 

biobank_data <- ukb_df("ukb_key")
Error: Some `col_types` are not S3 collector objects: 1

Any help would be greatly appreciated, and thanks again for your work so far!

Hannah

**Comment by kenhanscombe** [comment]
Hi Hannah,

I've just updated the read function to the faster `data.table::fread`. Please reinstall the updated development version and generate your .r and .tab files again (with UKB program ukb_conv), then try read your data in again.

Let me know me if this works for you.

All the best,

Ken

**Comment by curranth** [comment]
Hi Ken, 

Thanks for your quick response, I will give this a go and let you know how it goes!

Best,

Hannah

**Comment by muschellij2** [comment]
I encountered something similar in #6 and added a PR #7 to hopefully fix this.  I've encountered different types than UKBB had described (such as `Curve`) and put a warning in there to show you which types were encountered and defaults them to `character`.  This default may be dangerous, but it will at least allow the command to run.

**Comment by kenhanscombe** [comment]
Thank you. Merged changes.

Hannah – Does this solve your read problem? (Remember to re-generate your .tab and .r file if you've run any previous version of ukb_df on them.)

Ken
