### ISSUE TITLE
ukbxxx.enc file in ukbtools?

### ISSUE THREAD

**Issue by Shicheng-Guo** [kenhanscombe/ukbtools#33]
Hi ken, do you know how to download the ukbxxx.enc file mentioned by ukbtools?

```
ukb_unpack ukbxxxx.enc key
ukb_conv ukbxxxx.enc_ukb r
ukb_conv ukbxxxx.enc_ukb docs
```

Thanks.

Shicheng

**Comment by kenhanscombe** [comment]
You should have recieved an email with decryption key and instruction from the UK Biobank on where to download (UKB AMS) and how to decrypt your data.
