### ISSUE TITLE
Is there an option from ukbtools to automatically collapse cohorts into one column? 

### ISSUE THREAD

**Issue by garyzhubc** [kenhanscombe/ukbtools#36]
Is there an option from ukbtools to automatically collapse cohorts into one column? For example, collapsing

`"hdl_cholesterol_f30760_0_0" "hdl_cholesterol_f30760_1_0" ` 

to 

`"hdl_cholesterol_f30760"`

**Comment by kenhanscombe** [comment]
No, because there's no single best way to combine multiple _instances_ and _arrays_ (captured by the last two integers in the name). How you combine them, if at all, is phenotype dependent.
