### ISSUE TITLE
Column 1 error again

### ISSUE THREAD

**Issue by ZacharyLim1994** [kenhanscombe/ukbtools#37]
Hello,

i tried using your example datasset "ukbxxxx" and when i tried to use the icd_diagnosis, it came up with the error:

ukb_icd_diagnosis(mydata, id = "1", icd.version = 10) ## mydata is same as my_ukb_data just change to make typing easier
Error: Column 1 must be named.
Use .name_repair to specify repair.
Run `rlang::last_error()` to see where the error occurred.

is there something wrong i did? path = (my pc location)\ukbtools-master\ukbtools-master\inst\extdata

**Comment by kenhanscombe** [comment]
`ukb_icd_diagnosis` retrieves the diagnoses for an participant. The value for the argument `id` should be a valid participant `eid`.

**Comment by ZacharyLim1994** [comment]
ohh i get it, i used your example dataset ukbxxxx to see the icd_diagnosis but it doesnt work. i ended up having to use my real dataset and it works in the end. okk i am now trying out the rest now.
