### ISSUE TITLE
Trouble loading files into ukbtools

### ISSUE THREAD

**Issue by jameskozubek** [kenhanscombe/ukbtools#38]
Hello, 
I have created these file sets using ukbconv. 

ukb42106.html
ukb42106.tab 
ukb42106.r 

However, after installing the tools in R, I cannot seem to load them up. 
> getwd()
[1] "/mnt/BIOINFX/UK-Biobank"

> library(ukbtools)
> my_ukb_data <- ukb_df("ukb42106")
Error: Can't subset columns that don't exist.
✖ Location 2 doesn't exist.
ℹ There are only 1 column.
Run `rlang::last_error()` to see where the error occurred.

Backtrace:
  1. ukbtools::ukb_df("ukb42106")
  4. ukbtools::ukb_df_field(fileset, path = path)
  5. ukbtools:::fill_missing_description(html_table)
  7. tibble:::`[.tbl_df`(data[, "Description"], i)
  8. tibble:::vectbl_as_col_location(...)
 11. vctrs::vec_as_location(j, n, names)
 13. vctrs:::stop_subscript_oob(...)
 14. vctrs:::stop_subscript(...)
Run `rlang::last_trace()` to see the full context.

Backtrace:
     █
  1. ├─ukbtools::ukb_df("ukb42106")
  2. │ ├─ukb_df_field(fileset, path = path) %>% mutate(fread_column_type = col_type[col.type])
  3. │ └─ukbtools::ukb_df_field(fileset, path = path)
  4. │   └─ukbtools:::fill_missing_description(html_table)
  5. │     ├─data[, "Description"][i]
  6. │     └─tibble:::`[.tbl_df`(data[, "Description"], i)
  7. │       └─tibble:::vectbl_as_col_location(...)
  8. │         ├─tibble:::subclass_col_index_errors(...)
  9. │         │ └─base::withCallingHandlers(...)
 10. │         └─vctrs::vec_as_location(j, n, names)
 11. │           └─(function () ...
 12. │             └─vctrs:::stop_subscript_oob(...)
 13. │               └─vctrs:::stop_subscript(...)
 14. └─dplyr::mutate(., fread_column_type = col_type[col.type])

$ head ukb42106.r
# R program ukb42106.tab created 2021-06-07 by ukb2r.cpp Mar 14 2018 14:22:05

bd <- read.table("/mnt/BIOINFX/UK-Biobank/ukb42106.tab", header=TRUE, sep="\t")
lvl.0009 <- c(0,1)
lbl.0009 <- c("Female","Male")
bd$f.31.0.0 <- ordered(bd$f.31.0.0, levels=lvl.0009, labels=lbl.0009)
lvl.0008 <- c(1,2,3,4,5,6,7,8,9,10,11,12)
lbl.0008 <- c("January","February","March","April","May","June","July","August","September","October","November","December")
bd$f.52.0.0 <- ordered(bd$f.52.0.0, levels=lvl.0008, labels=lbl.0008)
bd$f.53.0.0 <- as.Date(bd$f.53.0.0)

head ukb42106.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
<style type="text/css">
body {font-family: Arial, Verdana, sans-serif; }
a:link {text-decoration: none; }
td {vertical-align: top;}
</style>
<title>UK Biobank : Application XXXXX</title>
</head>

**Comment by jameskozubek** [comment]
For some reason, I reinstalled it a second time and now its working. The issue was related to the install.

**Comment by kenhanscombe** [comment]
Thanks James. glad you managed to fix it.

Ken

**Comment by GiulioCentorame** [comment]
Hi there,
I keep encountering this error every often. I suspect it has to deal with the way the package is compiled, as it happens with GCC 5.4.0 but not with GCC 7.2.0 on our cluster.
