### ISSUE TITLE
How to handle multiple fields for the same variable?

### ISSUE THREAD

**Issue by jameskozubek** [kenhanscombe/ukbtools#39]
I'd like to write a covariates file using ukb_gen_write_plink such as ukb.variables = c("variable1", "variable2", "variable3") 
However, I am wondering if there is a way to collapse the serials fields, such that, for instance, I have 4 possible recordings taken for average monthly red wine intake:

average_monthly_red_wine_intake_f4407_0_0
average_monthly_red_wine_intake_f4407_1_0
average_monthly_red_wine_intake_f4407_2_0
average_monthly_red_wine_intake_f4407_3_0

Is there a way to just call it once such as "average_monthly_red_wine_intake_f4407" and to get ukbtools to report only the max,min, or most recent value? Or, in general, is the only way to do it to call for all of the 4 fields using the ukbtools, and then write my own script that collapses the fields in fam file so that I have "average_monthly_red_wine_intake" only once with my best value?

**Comment by kenhanscombe** [comment]
There's no single best way to combine multiple _instances_ and _arrays_ (captured by the last two integers in the variable namename). How you combine them, if at all, is phenotype dependent, e.g., multiple drugs, multiple diagnoses, repeated measures of a disease, or in your example average monthly wine intake on different occasions(?) . You'll have to decide if these can/should be combined and do that before writing for genetic analysis.
