### ISSUE TITLE
fread(): found and resolved improper quoting out of sample

### ISSUE THREAD

**Issue by GiulioCentorame** [kenhanscombe/ukbtools#40]
Hi Ken,
thank you for this package, I am using it extensively on my project and it's really great.

I have encountered an issue with a data point in my UKB application while importing the basket through `ukb_df()`, which causes a warning from `fread()` (with relative nonzero exit code) and a desperate attempt to fix the entry:

```
Warning message:
In data.table::fread(input = tab_location, sep = "\t", header = TRUE,  :
  Found and resolved improper quoting out-of-sample. First healed line 459278: <
<5893037   [...]>>. If the fields are not quoted (e.g. field separator does not appear within any field), try quote="" to avoid this warning.
```

The culprit is what I suspect to be an entry from the medical records, containing several escaped quotation marks. Removing them with `sed -e "s|\\\'||g" -e 's|\\\"||g' data.tab` solves the issue.
Not sure if you plan on doing something about it (as the solution is relatively trivial), but I thought it was worth letting you know.

**Comment by kenhanscombe** [comment]
Hi Giulio,

Glad you find the package useful.

Thanks for spotting this and providing a fix. Will see if I can bake your fix in to `ukb_df` when I get some time. (I should be able to just pass your `sed` line to fread to preprocess the file before reading)

All the best,

Ken
