### ISSUE TITLE
Installing UKBTOOLS using devtools

### ISSUE THREAD

**Issue by Sathish9** [kenhanscombe/ukbtools#41]
Hi

devtools::install_github("kenhanscombe/ukbtools", dependencies = TRUE)

When I use the above command I am getting the following error:

E> * checking for file ‘/nvme/pbs/tmpdir/pbs.202087.flashmgr2/RtmpCkMHkl/remotes615da87bc05/kenhanscombe-ukbtools-3dca23a/DESCRIPTION’ ... OK
E> * preparing ‘ukbtools’:
E> * checking DESCRIPTION meta-information ... OK
E> * installing the package to process help pages
E> * creating vignettes ... ERROR
E> Warning in engine$weave(file, quiet = quiet, encoding = enc) :
E>   Pandoc (>= 1.12.3) not available. Falling back to R Markdown v1.
E> Error: processing vignette 'explore-ukb-data.Rmd' failed with diagnostics:
E> The 'markdown' package should be installed and declared as a dependency of the 'ukbtools' package (e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'markdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
E> Execution halted

I do not have pandoc in the cluster.

How can I solve this problem?

Regards,

Sathish

**Comment by kenhanscombe** [comment]
By default `devtools::github_install` should not build the vignettes: `build_manual = FALSE`, `build_vignettes = FALSE`. The vignette is written in rmarkdown, which is declared as a dependency.

Maybe try creating a dedicated conda environment then try installing into that environment?
