### ISSUE TITLE
Writing permission required by "ukb_df()"?

### ISSUE THREAD

**Issue by KasperFischer** [kenhanscombe/ukbtools#42]
Hi

I am familiarizing myself with ukbtools, since I am going to pull out phenotypes from the data. However, I am running into a problematic permission issue.

```
my_ukb_data <- ukb_df("ukbxxxx", path = "/shared/ukb/data/path")


Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning messages:
1: `data_frame()` was deprecated in tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: In file(file, ifelse(append, "a", "w")) :
  cannot open file '/shared/ukb/data/path/ukbxxxx.r': Permission denied
```

Since I have both reading and execution permissions for the .r-file, this error message can only be caused by writing permissions. The problem is that I share this directory with other people, so I am worried if writing permissions can be an issue. Is it really true that ukb_df() requires writing permissions?

Alternatively is there another way to do this without writing to the files? 

Best regards,

**Comment by kenhanscombe** [comment]
Hi,

Please try installing the development version

`devtools::install_github("kenhanscombe/ukbtools", dependencies = TRUE)`
