### ISSUE TITLE
image processing functions

### ISSUE THREAD

**Issue by Shicheng-Guo** [kenhanscombe/ukbtools#43]
Hi Ken, 

Is there any image processing functions on the roadmap to be developed? 

Thanks

Shicheng

**Comment by kenhanscombe** [comment]
Hi Shicheng, sorry for the very late response. I hadn't planned any image processing functionality for ukbtools. I've been focused on an in-house application (ukbkings) for the institute I work at. I did have some ideas and changes I was thinking about making to ukbtools, but, with the UKB RAP now available I didn't think it was worth developing it any further.
