### ISSUE TITLE
Memory issues with ukb_df_full_join()

### ISSUE THREAD

**Issue by GiulioCentorame** [kenhanscombe/ukbtools#44]
Hi there,
Not sure how to report this and/or what kind of information to add, but I am encountering an awful lot of memory issues when using the function `ukb_df_full_join()` in an HPC environment, from memory leaks (OOM with ~100GB available per node) to segfaults.

Happy to provide all the information needed from my environment

Cheers

**Comment by kenhanscombe** [comment]
Hi,

What is your memory request and what is the size of your dataframes? Are you running this in batch or as an interactive session? (BTW, what resource management does your HPC use?)

Under the hood `ukb_df_full_join` is using `purrr:reduce` to combine your dataframes with a `dplyr::full_join`, on UKB `eid`. If the dataframes are big, you'll need lots of memeory. Is this actually what you want to do?

Before combining the data you may want to consider which variables (columns) you're interested in. I find end up processing the data separately, e.g., I might have HES diagnoses in a dataframe, medication in another, the outcome with associated covariates and QC variables I'm interested in in another, etc. I guess I'm saying you often have way more variables in your full UKB application than you want to use in any one particular study.

**Comment by GiulioCentorame** [comment]
Thanks for getting back so quickly! To answer your questions:

- It's 2 files, 8.3 and 22GB respectively.
- I am running this in batch, submitted through Snakemake. It submits a job running `set -euo pipefail; Rscript --vanilla myscript.R`. Weirdly enough, I can't reproduce it in an interactive session. 
- It's running under Slurm 21.08. My resource request is 100GB and serial.

I was trying to create a single object on disk for both files, in order to avoid reading the massive tab files from there every time (which is a bottleneck for most of my pipelines). I have been filtering the instances one by one now, it's just very slow for the way they're stored in the HPC.

Looking at the code, I am actually surprised this is happening at all, I will try to test if it happens with `dplyr::full_join` independently or it's on `purrr`'s side

**Comment by kenhanscombe** [comment]
Once you've read and processed each dataset you could save as them as rds for faster read into R. I still recommend selecting only the variables you're interested in.

Alternately, checkout [disk.frame](https://diskframe.com/index.html) for fast on-disk querying. Save your ukbtools processed dataframes as disk.frames which allows for much faster queries. Basically does a chunked read/query allowing you to pipe through dplyr verbs to filter, select, etc., then `dplyr::collect` to get a dataframe. I'd say this is the best solution if you're doing multiple reads in a (snakemake) workflow.
