### ISSUE TITLE
Error in node$parent$priority[, node$name] : subscript out of bounds

### ISSUE THREAD

**Issue by Nghiyalwa** [kenhanscombe/ukbtools#45]
Hi All,

Kindly help,

How can i fix Error in node$parent$priority[, node$name] : subscript out of bounds? Below i have attached my YAML file and AHP r code.
[solar.txt](https://github.com/kenhanscombe/ukbtools/files/8097998/solar.txt)

library(data.tree)
vignette(package = 'data.tree')

library(ahp)
pvAhp <- Load('solar.txt')
Calculate(pvAhp)
Visualize(pvAhp)
Analyze(pvAhp)
AnalyzeTable(pvAhp)

**Comment by kenhanscombe** [comment]
Perhaps you intended to post this somewhere else?
