### ISSUE TITLE
ukb_gen_samples_to_remove does not exist? 

### ISSUE THREAD

**Issue by ghost** [kenhanscombe/ukbtools#9]
Hello,

The ukbtools manual https://kenhanscombe.github.io/ukbtools/ describes the function ukb_gen_samples_to_remove

However when I try to use it, I get the follwoing error: 
Error in ukb_gen_samples_to_remove(my_relatedness_data, ukb_with_data = pheno$anxiety_self) : 
  could not find function "ukb_gen_samples_to_remove"

Other functions such as ukb_gen_rel_count work fine, though. I've re-installed ukbtools (just in case it was using an older version) but still not working.

Thanks,
J

**Comment by kenhanscombe** [comment]
Hi J,

That's odd. You've definitely got `ukbtools v0.11.0` installed? If you look at `help(package="ukbtools")` what version do you see? If `v0.11.0`, is `ukb_gen_samples_to_remove` not listed? Or type `ukbtools::ukb_gen_s` and tab autocomplete – nothing still? Let me know what you see.

Btw, not that this will give you a `could not find function` error, but `ukb_with_data` should be a "character vector of ukb eids with data on the phenotype of interest".

All the best,

Ken

**Comment by ghost** [comment]
Hi Ken,

Ok, I've double checked and it was the ukbtools v0.10.0 version. I've removed that one and downloaded the new one: Now it is working fine. Thank you!

Best wishes,
J

**Comment by kenhanscombe** [comment]
Thanks, J.
